### PR TITLE
fix: upgrade some dependencies and fix some security issues

### PR DESCRIPTION
**Pull request by jerem-guy**
Related to d3-dag issue https://github.com/erikbrinkman/d3-dag/issues/82
I was having webpack error during build of a project using `react-d3-dag` : `Critical dependency: the request of a dependency is an expression`. I reproduced this error with the demo. It seems like upgrading to last version of `d3-dag` (0.9.1) is fixing the issue.
Can you please merge this to main branch and publish a new release ?

Change note from 0.8 to 0.9 of d3-dag : https://github.com/erikbrinkman/d3-dag#updating-from-08-to-09

Cheers,
Jérémie

### CODE REVIEW

**Comment by jerem-guy** [comment]
I have upgraded some dependencies and fixed some security issues with npm audit fix. I have checked with tests and demo and it looks like it didn't break anything (at least from what I see !). Would be nice to add a DAG example but I did not have time yet :)

**Comment by jerem-guy** [comment]
Hello @forivall,
Is there any chance that you have time to look at this soon ?
Cheers,
Jérémie

**Comment by forivall** [comment]
Sorry for the delay. @guy-j could you take a look at the eslint issue in CI? i think some version combination is causing this issue, i tried to bump a few other deps and didnt solve the issue. I'll try a few other update combos, but its worth it for you to try as well.

**Comment by forivall** [comment]
I bumped _just_ the actual dependencies, and left the dev dependencies alone, and that works fine. i published v0.1.2, let me know if that works for you. In the future, please make sure that tests and such still pass 😅 .

**Comment by jerem-guy** [comment]
Thanks a lot ! Sorry for the linting, I tried the tests but forgot totally the linting ...
I will fix it as soon as I have a minute to work on it.

**Comment by jerem-guy** [comment]
> I bumped _just_ the actual dependencies, and left the dev dependencies alone, and that works fine. i published v0.1.2, let me know if that works for you. In the future, please make sure that tests and such still pass 😅 .

It works perfectly with the v0.1.2 ! No more warning :) Thanks again

**Comment by jerem-guy** [comment]
Hello again @forivall, 

I had time to work on that again and I fixed the linting issue. I could not go too deep into the eslint upgrade problem today so I have left it as it was. This PR still fixes some security issues, but not all. I did not upgrade d3, eslint and husky.
I did not know you were updating from the upstream (react-d3-tree) which is good ! I guess I could have upgraded dependencies there too but I did not want to break anything :D

Cheers,
Jérémie

**Comment by forivall** [comment]
Yeah, luckily, merging in upstream with dependency changes is the easy part of merging upstream, so no worries!

**Pull request merged**
